baseURL = "https://nyupau.github.io/docs/"
languageCode = "en-us"
title = "NYU Predictive Analytics Unit"
theme = "startbootstrap_clean_blog"
canonifyurls = true
paginate = 10.0
copyright = "Code released under the Apache 2.0 license."
publishDir = "docs"

[params]
DateForm = "Jan 2, 2006"
Description = "Our Lab website"
email = "predictiveanalytics@nyumc.org"
postSummariesFrontPage = 8.0
showReadTime = true
customCSS = [
  "<absolute path to CSS>",
  "/static/css/test.css",
  "/static/css/avatar.css",
  "/static/css/images.css", 
  "/css/avatar.css",
  "css/avatar.css",
  "<or just load it off the internet>"
]

  [[params.social]]
  title = "twitter"
  url = "https://twitter.com/nyulmc_predict"

  [[params.social]]
  title = "github"
  url = "https://github.com/nyupau"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "home"
  url = "/"
  weight = -300.0

  [[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "blog"
  url = "/posts/"
  weight = -200.0

  [[menu.main]]
  identifier = "team"
  name = "our team"
  url = "/team/"
  weight = -100.0

  [[menu.main]]
  identifier = "about"
  name = "about us"
  url = "/about/"
  weight = -280.0
